image:
  file: .gitpod.dockerfile

ports:
- port: 8080

tasks:
- command:    mkdir /workspace/my-gitpod-of-edge-impulse/logs                                                                    &&
              touch /workspace/my-gitpod-of-edge-impulse/logs/gitpod-install-log.txt                                             &&
       

              echo "Starting .gitpod.yml installation" &>>  /workspace/my-gitpod-of-edge-impulse/logs/gitpod-install-log.txt     &&
 

                           
              cd /workspace/my-gitpod-of-edge-impulse/edge-impulse/local-build-firmware/portenta                             &&
              chmod +x a00-get-lora-example.sh                                                                               &&
              chmod +x a01-portenta.sh                                                                                       &&
              chmod +x arduino-build.sh                                                                                      &&
              
              
              cd /workspace/my-gitpod-of-edge-impulse/edge-impulse/local-build-firmware/etaCompute                           &&
              git clone https://github.com/edgeimpulse/example-standalone-inferencing-ecm3532.git    eta-compile             &&         
              mv a01-eta.sh eta-compile/                                                                                     &&         
              cd eta-compile                                                                                                 &&         
              chmod +x a01-eta.sh                                                                                            &&   
                            
                            
              cd /workspace/my-gitpod-of-edge-impulse/edge-impulse/local-build-firmware/siliconLabs                                   &&
              git clone https://github.com/edgeimpulse/example-standalone-inferencing-silabs-tb-sense-2.git   silicon-labs-compile    &&     
              mv a01-siliconLabs.sh   silicon-labs-compile/                                                                           &&
              cd silicon-labs-compile                                                                                                 &&
              mkdir ei-workspace                                                                                                      &&
              chmod +x a01-siliconLabs.sh                                                                                             &&
                        
                            
              cd /workspace/my-gitpod-of-edge-impulse                                                                       &&
              cd /workspace/my-gitpod-of-edge-impulse/edge-impulse/local-build-firmware/nordic                              &&
              git clone https://github.com/edgeimpulse/firmware-nrf52840-5340-dk   nordic-compile                           &&     
              mv a01-nordic-nrf5280.sh   nordic-compile/                                                                    &&
              mv a02-nordic-nrf5340.sh   nordic-compile/                                                                    &&
              cd nordic-compile                                                                                             &&
              chmod +x a01-nordic-nrf5280.sh                                                                                &&
              chmod +x a02-nordic-nrf5340.sh                                                                                &&
              
              
              cd /home/gitpod                                                                                               &&
              curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh                       &&
              python3 -m pip install mbed-cli  west                                                                         &&
              ./workspace/my-gitpod-of-edge-impulse/edge-impulse/local-build-firmware/portenta/arduino-build.sh             &&
              
              cd /workspace/my-gitpod-of-edge-impulse                                                                       &&                                                                                

              echo "Ending .gitpod.yml installation"  &>>   /workspace/my-gitpod-of-edge-impulse/logs/gitpod-install-log.txt    
              
              
     
